// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeebLibraryApi.Models;

namespace WeebLibraryApi.Migrations
{
    [DbContext(typeof(WeebLibraryContext))]
    [Migration("20191002054920_Added_registerdate_to_usertable")]
    partial class Added_registerdate_to_usertable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WeebLibraryApi.Models.AnimeManga", b =>
                {
                    b.Property<int>("AnimeMangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MalCode")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimeMangaId");

                    b.HasIndex("MalCode")
                        .IsUnique();

                    b.ToTable("AnimeMangas");
                });

            modelBuilder.Entity("WeebLibraryApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2").HasDefaultValue(DateTime.Now);

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WeebLibraryApi.Models.UserAnimeManga", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AnimeMangaId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "AnimeMangaId");

                    b.HasIndex("AnimeMangaId");

                    b.ToTable("UserAnimeMangas");
                });

            modelBuilder.Entity("WeebLibraryApi.Models.UserAnimeManga", b =>
                {
                    b.HasOne("WeebLibraryApi.Models.AnimeManga", "AnimeManga")
                        .WithMany()
                        .HasForeignKey("AnimeMangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeebLibraryApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
